spring:
  application:
    name: db-connection-status

# Server configuration
server:
  port: 8080

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.example.dbconnectionstatus: DEBUG